/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Image, Text, View } from "@aws-amplify/ui-react";
import ControlsSelectDefault from "./ControlsSelectDefault";
export default function PopoversLargeInlineImage(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="256px"
      height="456px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "PopoversLargeInlineImage")}
      {...rest}
    >
      <View
        width="256px"
        height="456px"
        {...getOverrideProps(overrides, "Popovers / Settings / Default")}
      ></View>
      <ControlsSelectDefault
        width="224px"
        height="56px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="128px"
        left="16px"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Controls / Select / Default")}
      ></ControlsSelectDefault>
      <Text
        fontFamily="Avenir Next"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="24px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="224px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="16px"
        left="16px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Edit image"
        {...getOverrideProps(overrides, "Edit image")}
      ></Text>
      <Image
        width="224px"
        height="64px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="48px"
        left="16px"
        borderRadius="4px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "Rectangle 2")}
      ></Image>
      <View
        padding="0px 0px 0px 0px"
        width="224px"
        height="64px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="200px"
        left="16px"
        {...getOverrideProps(overrides, "Group 4")}
      >
        <Text
          fontFamily="Avenir Next"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="24px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="224px"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          bottom="40px"
          left="0px"
          right="0px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Overlay colour"
          {...getOverrideProps(overrides, "Overlay colour")}
        ></Text>
        <View
          width="32px"
          height="32px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          bottom="0px"
          left="0px"
          right="192px"
          border="1px SOLID rgba(239,239,239,1)"
          borderRadius="4px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(255,255,255,1)"
          {...getOverrideProps(overrides, "Rectangle 2.2")}
        ></View>
        <Text
          fontFamily="Avenir Next"
          fontSize="12px"
          fontWeight="500"
          color="rgba(141,144,145,1)"
          lineHeight="24px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="88px"
          height="32px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          bottom="0px"
          left="40px"
          right="96px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Choose"
          {...getOverrideProps(overrides, "Choose")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="224px"
        height="72px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="280px"
        left="16px"
        {...getOverrideProps(overrides, "Group 3")}
      >
        <Text
          fontFamily="Avenir Next"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="24px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="224px"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          bottom="48px"
          left="0px"
          right="0px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Padding"
          {...getOverrideProps(overrides, "Padding")}
        ></Text>
        <View
          padding="0px 0px 0px 0px"
          width="224px"
          height="40px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="32px"
          left="0px"
          {...getOverrideProps(overrides, "Group11414640")}
        >
          <View
            width="224px"
            height="40px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            bottom="0px"
            left="0px"
            right="0px"
            borderRadius="4px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(239,239,239,1)"
            {...getOverrideProps(overrides, "Rectangle 2.311414641")}
          ></View>
          <View
            width="32px"
            height="32px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            bottom="4px"
            left="4px"
            right="188px"
            borderRadius="4px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(0,0,0,1)"
            {...getOverrideProps(overrides, "Rectangle 311414642")}
          ></View>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="400"
            color="rgba(255,255,255,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="4px"
            right="188px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="0"
            {...getOverrideProps(overrides, "0")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(0,0,0,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="40px"
            right="152px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="16"
            {...getOverrideProps(overrides, "20")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(0,0,0,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="72px"
            right="120px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="24"
            {...getOverrideProps(overrides, "40")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(0,0,0,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="24px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="104px"
            right="96px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="32"
            {...getOverrideProps(overrides, "60")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(0,0,0,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="136px"
            right="56px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="40"
            {...getOverrideProps(overrides, "80")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(141,144,145,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="48px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="168px"
            right="8px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Enter"
            {...getOverrideProps(overrides, "Enter")}
          ></Text>
        </View>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="224px"
        height="72px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="368px"
        left="16px"
        {...getOverrideProps(overrides, "Group 2")}
      >
        <Text
          fontFamily="Avenir Next"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="24px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="224px"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          bottom="48px"
          left="0px"
          right="0px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Ratio"
          {...getOverrideProps(overrides, "Ratio")}
        ></Text>
        <View
          padding="0px 0px 0px 0px"
          width="224px"
          height="40px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="32px"
          left="0px"
          {...getOverrideProps(overrides, "Group11414651")}
        >
          <View
            width="224px"
            height="40px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            bottom="0px"
            left="0px"
            right="0px"
            borderRadius="4px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(239,239,239,1)"
            {...getOverrideProps(overrides, "Rectangle 2.311414652")}
          ></View>
          <View
            width="40px"
            height="32px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            bottom="4px"
            left="4px"
            right="180px"
            borderRadius="4px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(0,0,0,1)"
            {...getOverrideProps(overrides, "Rectangle 311414653")}
          ></View>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="400"
            color="rgba(255,255,255,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="40px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="4px"
            right="180px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Auto"
            {...getOverrideProps(overrides, "Auto")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(0,0,0,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="40px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="44px"
            right="140px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="2:1"
            {...getOverrideProps(overrides, "2:1")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(0,0,0,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="40px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="84px"
            right="100px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="3:2"
            {...getOverrideProps(overrides, "3:2")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(0,0,0,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="40px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="124px"
            right="60px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="4:3"
            {...getOverrideProps(overrides, "4:3")}
          ></Text>
          <Text
            fontFamily="Avenir Next"
            fontSize="12px"
            fontWeight="500"
            color="rgba(0,0,0,1)"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="40px"
            height="16px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            bottom="12px"
            left="164px"
            right="20px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="1:1"
            {...getOverrideProps(overrides, "1:1")}
          ></Text>
        </View>
      </View>
      <View
        width="24px"
        height="24px"
        {...getOverrideProps(overrides, "Icons / Actions / Edit")}
      ></View>
    </View>
  );
}
