import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import { Amplify } from "aws-amplify";
import amplifyConfig from "../amplifyConfig";

import "@aws-amplify/ui-react/styles.css";

Amplify.configure(amplifyConfig);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
